config/routes.rb
Store::Application.routes.draw do
  resources :products do
    resources :variants, :only => [:index]
  end
  root :to => 'products#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :products

  attr_accessible :name

  validates :name, presence: true
end

app/models/product.rb
class Product < ActiveRecord::Base
  before_save :set_defaults

  has_many :variants

  belongs_to :category

  attr_accessible :active, :description, :name, :price, :category_id

  validates :name, :category_id, presence: true

  def set_defaults
    self.active ||= false
  end
end

app/models/variant.rb
class Variant < ActiveRecord::Base
  belongs_to :product
  attr_accessible :product_id, :size, :color
  validates :size, :color, :product_id, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def new
    @product = Product.new active: true
    @categories = Category.all
    @variant = Variant.all
  end

  def create
    @product = Product.new params[:product]

    if @product.valid?
      @product.save
      return redirect_to products_path, notice: "Your product #{@product.name} has been created!"
    end

   @categories = Category.all
   render :new
  end

  def show
    @product = Product.find_by_id params[:id]
  end

  def edit
    @product = Product.find_by_id params[:id]
    @categories = Category.all
  end

  def update
    @product = Product.find_by_id params[:id]

    if @product.update_attributes params[:product]
      return redirect_to products_path, notice: "Your product #{@product.name} has been updated!"
    end

    @categories = Category.all
    render :edit
  end

end

app/controllers/variants_controller.rb
class VariantsController < ApplicationController
  def index
    product = Product.find_by_id params[:product_id]
    @variants = product.variants
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/variants_helper.rb
module VariantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Store</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<% if product.errors.any? %>
<h3>Uppss we have a problem</h3>
<% end %>
<%= form_for product do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<span class='error'><%= product.errors[:name].join(', ') %></span>
<br/>
<%= f.label :category_id %>
<%= collection_select :product, :category_id, categories, :id, :name %>
<span class='error'><%= product.errors[:category_id].join(', ') %></span>
<br/>
<%= f.label :descritpion %>
<%= f.text_area :description, cols: 30, rows: 5 %>
<br/>
<%= f.label :price %>
<%= f.text_field :price %>
<span class='error'><%= product.errors[:price].join(', ') %></span>
<br/>
<%= f.label :active %>
<%= f.check_box :active, checked_value: true, unchecked_value: false %>
<br/>
<%= f.submit 'Save' %>
<% end %>

app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= render partial: 'form', locals: { product: @product, categories: @categories } %>

app/views/products/index.html.erb
<h1>Products list</h1>
<span><%= flash[:notice] %></span>
<p><%= link_to 'New product', new_product_path %></p>
<ul>
<% @products.each do |product| %>
<li id='<%= "product_#{product.id}" %>'>
<%= product.name %> | <%= link_to 'Show', product %>
</li>
<% end %>
</ul>

app/views/products/new.html.erb
<h1>New product</h1>
<%= render partial: 'form', locals: { product: @product, categories: @categories, } %>

app/views/products/show.html.erb
<h1>Product</h1>
<% if @product.nil? %>
<h3>Product not found</h3>
<% else %>
<p><%= link_to 'Edit', edit_product_path(@product) %></p>
<p>
<span>Name: </span><%= @product.name %>
</p>
<p>
<span>Category: </span><%= @product.try(:category).try(:name) %>
</p>
<p>
<span>Description: </span><%= @product.description %>
</p>
<p>
<span>Price: </span><%= @product.price %>
</p>

<p><%= link_to 'Variants', product_variants_path(@product) %></p>
<p>
<% end %>
<%= link_to 'Back', :back %>

app/views/variants/index.html.erb
<h1>Variants for <%= @variants.first.product.name%></h1>
<p><%= link_to 'Product', @variants.first.product %></p>
<ul>
<% @variants.each do |variant| %>
<li>
Size: <%= variant.size %>
</li>
<li>
Color: <%= variant.color %>
</li>
<br />
<hr>
<% end %>
</ul>